apiVersion: v1
kind: ConfigMap
metadata:
  name: upfedge2-cmap
  labels:
    nf-type: upfedge2
data:
  upf.yaml: |
    logger:
        file: /open5gs/upf.log
    upf:
        pfcp:
           dev: {{ .Values.k8s.interface }} # Host IP
        gtpu:
           dev: {{ .Values.k8s.interface }} # Host IP
        subnet:
          - addr: 10.47.0.1/16
            dnn: {{ .Values.dnn3 }}
            dev: ogstun3