apiVersion: v1
kind: Service
metadata:
  name: amari-sf
  labels:
    amarisoft: amari-sf
  namespace: monitoring
spec:
  selector:
     amarisoft: amari-sf
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 80
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: amari-sf
  labels:
    amarisoft: amari-sf
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      amarisoft: amari-sf
  template:
    metadata:
      labels:
        amarisoft: amari-sf
    spec:    
      containers:
        - name: amari-sf
          image: "{{ .Values.amarisoftsf.image.repository }}:{{ .Values.amarisoftsf.image.tag }}"
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodes.monitor }}